settings:
  path_to_logs: 
    # list all paths to logs that you use in this cluster. A path specified below should match a node's log directory at least once
    - /var/log/cassandra
  path_to_configs: 
    # list all paths to configs that you use in this cluster. A path specified below should match a node's log directory at least once
    - /etc/dse/cassandra/
  # TODO can get using nodetool like is done in TableAnalyzer/cfstats.receive.py#42, `nodetool version`
  # one of: "dse", "cassandra" (only supporting those for now, and maybe that's enough)
  cassandra_distribution: dse

