- hosts: cassandra
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - cassandra-exporter-install
    - tablesnap-install
    - filebeat
    - enable-jmx

###
### GENERATE DOCKER ARTIFACTS, GATHER CLUSTER INFO
###
- hosts: cassandra[0]
  become: true
  become_method: sudo
  become_user: "{{ cassandra_ops_os_user }}"
  run_once: true
  tasks:
    - name: nodetool describecluster
      command: "{{ nodetool_exec }} -u {{ cassandra_shell_user }} -pw {{ cassandra_shell_password }} describecluster"
      register: nodetool_output

    - set_fact: cassandra_cluster_name={{ nodetool_output.stdout | regex_search("Name:\s(.*)\s", '\\1', multiline=True, ignorecase=False) }} cacheable=yes

    - debug:
        msg: "Determining cluster name: {{ cassandra_cluster_name[0] }}"

###
### GENERATE DOCKER ARTIFACTS, GENERATE FILES
###
### - hosts: localhost
###   tasks:
###     - copy: content="{{ hostvars[groups['cassandra'][0]]['ansible_all_ipv4_addresses'] }}" dest=/tmp/11.json

- hosts: localhost
  tasks:
    - set_fact: cassandra_node_ip={{ hostvars[groups['cassandra'][0]]['private_ip'] }}
    - set_fact: cassandra_cluster_name={{ hostvars[groups['cassandra'][0]]['cassandra_cluster_name'][0] }}

- hosts: localhost
  roles:
      ### keep "docker-compose" on top because it sets facts needed by the others
    - docker-compose
    - prometheus
    - grafana
