cassandra_exporter_agent_url: https://github.com/instaclustr/cassandra-exporter/releases/download/v0.9.10/cassandra-exporter-agent-0.9.10.jar
cassandra_exporter_url: https://github.com/criteo/cassandra_exporter/releases/download/2.3.2/cassandra_exporter-2.3.2-all.jar
