---
- name: install python3-pip and packages (yum)
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - "python3-pip"
    - "python-devel"
    - "shiboken-python3*"
  when: ansible_os_family == "RedHat"
  tags: ["medusa"]

- name: install virtualenv and packages
  command: "{{ item }}"
  with_items:
    - "pip3 install --upgrade pip"
    - "pip3 install virtualenv zipp"
  tags: ["medusa"]

- name: create virtual env && install cassandra medusa
  command: "{{ item }}"
  with_items:
    - "/usr/local/bin/virtualenv -p python3 {{ tools_install_folder }}/venv/python3-cassandra-medusa"
    - "{{ tools_install_folder }}/venv/python3-cassandra-medusa/bin/pip3 install cassandra-medusa[S3]"
  tags: ["medusa"]

